(() => {
  'use strict';

  const KEY = 'chalets_app_state_v5';
  const OLD_KEYS = ['chalets_app_state_v4', 'chalets_app_state_v3'];
  const RECOVERY_KEYS = ['chalet_booking_sync_v6_state','chalet_booking_sync_v7_state','chalet_booking_sync_v8_state','chalets_booking_v2','chalets_booking_v1','chalets_app_state_v3','chalets_booking_ready_v1','safe_backup_before_v9','v10_backup_before_recovery','v11_backup_before_local_restore'];
  const QUEUE_KEY = 'chalets_sync_queue_v2';
  const DB_NAME = 'chaletsDB';
  const STORE = 'kv';
  const COLORS = [['#d4af5f','#8c6a2d'],['#73a76b','#456f43'],['#6ea8fe','#315f9e'],['#d46a5d','#8f3d35'],['#d59a55','#8a5b2e'],['#52b7aa','#2f736d']];
  const MONTHS = ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
  const DAYS = ['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
  const DEFAULT_SETTINGS = {name:'شاليهات الفخامة',tag:'نظام متكامل',phone:'',checkIn:'15:00',checkOut:'12:00',terms:'• وقت الدخول والخروج حسب السند.\n• المحافظة على نظافة الشاليه ومحتوياته.',supabaseUrl:'',supabaseAnon:''};
  const DEFAULT_STATE = {chalets:[],bookings:[],settings:{...DEFAULT_SETTINGS},theme:'dark',lastSync:null};
  const $ = (id) => document.getElementById(id);
  const qsa = (sel) => Array.from(document.querySelectorAll(sel));
  const isDev = ['localhost','127.0.0.1'].includes(location.hostname);
  const log = (...a) => { if (isDev) console.log('[booking-app]', ...a); };

  let state = structuredClone(DEFAULT_STATE);
  let db = null, supabase = null, session = null, user = null;
  let realtime = [], editingBookingId = null, editingChaletId = null, selectedColor = 0;
  let syncTimer = null, syncing = false;

  function uid(){ return crypto.randomUUID ? crypto.randomUUID() : (Date.now().toString(36)+Math.random().toString(36).slice(2,10)); }
  function todayISO(d=new Date()){ return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
  function parseDate(s){ return new Date(`${s}T00:00:00`); }
  function nights(a,b){ if(!a||!b) return 0; return Math.round((parseDate(b)-parseDate(a))/86400000); }
  function fmtDate(s){ const d=typeof s==='string'?parseDate(s):s; if(!d||isNaN(d)) return '—'; return `${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()}`; }
  function shortDate(s){ const d=parseDate(s); return `${d.getDate()}/${d.getMonth()+1}`; }
  function money(n){ return new Intl.NumberFormat('en-US').format(Math.round(Number(n)||0)); }
  function esc(s){ return String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
  function now(){ return new Date().toISOString(); }
  function activeChalets(){ return state.chalets.filter(c => !c.deleted_at && c.is_active !== false); }
  function activeBookings(){ return state.bookings.filter(b => !b.deleted_at); }
  function chaletName(id){ return state.chalets.find(c=>c.id===id)?.name || '—'; }
  function getSettings(){ return {...DEFAULT_SETTINGS, ...(state.settings||{})}; }
  function statusText(s){ return {confirmed:'مؤكد',pending:'معلق',cancelled:'ملغي',completed:'مكتمل',active:'حالي',upcoming:'قادم',past:'سابق'}[s] || s || '—'; }
  function businessStatus(b){ if(['cancelled','pending','completed'].includes(b.status)) return b.status; const t=todayISO(); if(b.check_in<=t && b.check_out>t) return 'active'; if(b.check_in>t) return 'upcoming'; return 'past'; }
  function setText(id,v){ const el=$(id); if(el) el.textContent = v; }
  function toast(msg,type='ok'){ const el=$('toast'); if(!el) return; el.textContent=msg; el.className=`toast on ${type}`; clearTimeout(toast._t); toast._t=setTimeout(()=>el.className='toast',3200); }
  function setSaveStatus(text,type='ok'){ const el=$('saveStatus'); if(!el) return; el.textContent='● '+text; el.className='status-pill '+(type==='bad'?'bad':type==='warn'?'warn':''); }
  function setCloudStatus(text,type='warn'){ setText('cloudStatusText', text); const top=$('cloudTop'); if(top) top.title=text; if(type==='bad') setSaveStatus('خطأ في المزامنة','bad'); }

  function openDB(){ return new Promise(resolve=>{ if(!indexedDB) return resolve(null); const req=indexedDB.open(DB_NAME,1); req.onupgradeneeded=()=>{ if(!req.result.objectStoreNames.contains(STORE)) req.result.createObjectStore(STORE); }; req.onsuccess=()=>resolve(req.result); req.onerror=()=>resolve(null); }); }
  function dbGet(key){ return new Promise(resolve=>{ if(!db) return resolve(null); const req=db.transaction(STORE).objectStore(STORE).get(key); req.onsuccess=()=>resolve(req.result); req.onerror=()=>resolve(null); }); }
  function dbSet(key,val){ return new Promise(resolve=>{ if(!db) return resolve(); const tx=db.transaction(STORE,'readwrite'); tx.objectStore(STORE).put(val,key); tx.oncomplete=resolve; tx.onerror=resolve; }); }

  function normalizeOld(raw){
    const base = structuredClone(DEFAULT_STATE); const old = raw || {}; const settings = old.settings || old.set || {};
    base.settings = {...DEFAULT_SETTINGS,name:settings.name||DEFAULT_SETTINGS.name,tag:settings.tag||DEFAULT_SETTINGS.tag,phone:settings.phone||DEFAULT_SETTINGS.phone,checkIn:settings.checkIn||settings.in||DEFAULT_SETTINGS.checkIn,checkOut:settings.checkOut||settings.out||DEFAULT_SETTINGS.checkOut,terms:settings.terms||DEFAULT_SETTINGS.terms,supabaseUrl:settings.supabaseUrl||window.CHALETS_SUPABASE_URL||'',supabaseAnon:settings.supabaseAnon||window.CHALETS_SUPABASE_ANON_KEY||''};
    base.theme = old.theme || 'dark';
    base.chalets = (old.chalets || []).map(c => ({id:String(c.id||uid()),name:String(c.name||'شاليه'),capacity:Number(c.capacity??c.cap??1),price:Number(c.price||0),description:String(c.description??c.desc??''),color:Number(c.color||0),is_active:c.is_active!==false,created_at:c.created_at||now(),updated_at:c.updated_at||now(),deleted_at:c.deleted_at||null}));
    base.bookings = (old.bookings || []).map((b,i)=>({id:String(b.id||uid()),booking_no:String(b.booking_no||b.no||`${new Date().getFullYear()}-${String(i+1).padStart(4,'0')}`),chalet_id:String(b.chalet_id||b.ch||''),customer_name:String(b.customer_name||b.name||''),customer_phone:String(b.customer_phone||b.phone||''),check_in:String(b.check_in||b.in||todayISO()),check_out:String(b.check_out||b.out||todayISO(new Date(Date.now()+86400000))),nights:Number(b.nights??b.n??1),guests:Number(b.guests??b.g??1),total:Number(b.total||0),paid:Number(b.paid||0),status:String(b.status||'confirmed'),notes:String(b.notes||''),created_at:b.created_at||now(),updated_at:b.updated_at||now(),deleted_at:b.deleted_at||null})).filter(b=>b.chalet_id);
    return base;
  }

  function hasTulum(x){ return /تولوم|tulum/i.test(String(x||'')); }
  function hasSky(x){ return /سكاي|sky/i.test(String(x||'')); }
  function looksSeedOnly(st){ const names=(st.chalets||[]).map(c=>c.name||'').join(' '); const b=(st.bookings||[]).filter(x=>!x.deleted_at).length; return b===0 && /الواحة/.test(names) && /الياسمين/.test(names) && !hasTulum(names) && !hasSky(names); }
  function stateScore(st){ const names=(st.chalets||[]).map(c=>c.name||'').join(' '); const b=(st.bookings||[]).filter(x=>!x.deleted_at).length; const c=(st.chalets||[]).filter(x=>!x.deleted_at).length; return (b*10000)+(c*100)+(hasTulum(names)?50000:0)+(hasSky(names)?50000:0); }
  function listRecoveryCandidates(){
    const keys=new Set([...OLD_KEYS, KEY, ...RECOVERY_KEYS]);
    for(let i=0;i<localStorage.length;i++){ const k=localStorage.key(i); if(k&&/(chalet|chalets|booking|sync|backup|recovery|state|workspace|v9|v10|v11)/i.test(k)) keys.add(k); }
    const out=[];
    keys.forEach((k)=>{
      const raw=localStorage.getItem(k); if(!raw) return;
      try{ const obj=JSON.parse(raw); const st=normalizeOld(obj.state||obj.data||obj); const names=(st.chalets||[]).map(x=>x.name||'').join(' '); const item={key:k,state:st,chalets:activeCount(st.chalets),bookings:activeCount(st.bookings),seed:looksSeedOnly(st),tulum:hasTulum(names),sky:hasSky(names)}; item.score=stateScore(st); out.push(item);}catch{}
    });
    out.sort((a,b)=>b.score-a.score);
    return out;
  }
  function activeCount(arr){ return (arr||[]).filter(x=>!x.deleted_at).length; }
  function hasRealData(st){ return activeCount(st.chalets)>0 || activeCount(st.bookings)>0 || hasTulum(JSON.stringify(st)) || hasSky(JSON.stringify(st)); }
  function pickBestCandidate(cands){ return cands.find(x=>!x.seed && (x.bookings>0 || x.tulum || x.sky)) || cands.find(x=>!x.seed && hasRealData(x.state)) || null; }
  function backupBeforeOverwrite(tag='overwrite'){ localStorage.setItem(`v11_backup_before_local_restore_${Date.now()}_${tag}`, JSON.stringify({at:now(), state})); }

  async function loadLocal(){
    db=await openDB(); let raw=await dbGet(KEY); if(!raw){try{raw=JSON.parse(localStorage.getItem(KEY)||'')}catch{}}
    if(!raw){ for(const k of OLD_KEYS){try{raw=JSON.parse(localStorage.getItem(k)||''); if(raw){localStorage.setItem(`${k}_backup_before_migration`,JSON.stringify(raw)); break;}}catch{}} }
    state=normalizeOld(raw);
    const cands=listRecoveryCandidates();
    const best=pickBestCandidate(cands);
    if((!hasRealData(state) || looksSeedOnly(state)) && best){ state=best.state; }
    if(!hasRealData(state)) seed();
    await saveLocalOnly(false);
  }
  function seed(){ state.chalets=[{id:uid(),name:'شاليه الواحة',capacity:6,price:600,description:'مسبح خاص وجلسة خارجية',color:0,is_active:true,created_at:now(),updated_at:now(),deleted_at:null},{id:uid(),name:'شاليه الياسمين',capacity:4,price:450,description:'غرفتان وحديقة صغيرة',color:1,is_active:true,created_at:now(),updated_at:now(),deleted_at:null}]; }
  async function saveLocalOnly(show=true){ localStorage.setItem(KEY,JSON.stringify(state)); await dbSet(KEY,state); if(show) setSaveStatus('تم الحفظ'); }
  function readQueue(){ try{return JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]')}catch{return[]} }
  function writeQueue(q){ localStorage.setItem(QUEUE_KEY,JSON.stringify(q)); }
  function enqueue(op){ const q=readQueue(); q.push({...op,id:uid(),created_at:now(),retry:0}); writeQueue(q.slice(-200)); }
  async function saveAndQueue(op){ await saveLocalOnly(); enqueue(op); renderAll(); syncSoon(); }

  function initSupabase(){ const s=getSettings(); const url=(s.supabaseUrl||window.CHALETS_SUPABASE_URL||'').trim(); const anon=(s.supabaseAnon||window.CHALETS_SUPABASE_ANON_KEY||'').trim(); if(!url||!anon||!url.startsWith('https://')){supabase=null;setCloudStatus('تحقق من إعدادات Supabase','warn');return false;} if(!window.supabase?.createClient){setCloudStatus('تعذر تحميل مكتبة Supabase','bad');return false;} supabase=window.supabase.createClient(url,anon,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:localStorage}}); return true; }
  async function initAuth(){ if(!initSupabase()) return updateAuthUI(); const {data,error}=await supabase.auth.getSession(); if(error) console.error(error); session=data?.session||null; user=session?.user||null; updateAuthUI(); supabase.auth.onAuthStateChange(async (_event,newSession)=>{session=newSession; user=newSession?.user||null; updateAuthUI(); if(user){toast('تم تسجيل الدخول'); await startCloudSync(true);} else setCloudStatus('محلي فقط','warn');}); if(user) await startCloudSync(false); }
  async function sendMagicLink(){ if(!supabase&&!initSupabase()) return toast('تحقق من إعدادات Supabase','bad'); const email=$('loginEmail').value.trim(); if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return setAuthMessage('أدخل بريد صحيح','bad'); const btn=$('sendLogin'); btn.disabled=true; setAuthMessage('جاري إرسال رابط التحقق...',''); const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin+window.location.pathname,shouldCreateUser:true}}); btn.disabled=false; if(error){console.error(error); setAuthMessage('فشل إرسال رابط التحقق: '+arabicError(error.message),'bad'); toast('فشل إرسال رابط التحقق','bad'); return;} setAuthMessage('تم إرسال رابط التحقق إلى بريدك','ok'); toast('تم إرسال رابط التحقق إلى بريدك'); }
  function arabicError(m){ if(!m) return 'تحقق من الإعدادات'; if(m.includes('rate')) return 'انتظر 60 ثانية قبل طلب رابط جديد'; if(m.includes('Invalid')) return 'تحقق من البريد أو إعدادات Supabase'; return m; }
  function setAuthMessage(text,type=''){ const el=$('authMessage'); if(el){el.textContent=text; el.style.color=type==='bad'?'var(--red)':type==='ok'?'var(--ok)':'var(--muted)';} }
  async function logout(){ if(!supabase) return; const {error}=await supabase.auth.signOut(); if(error) return toast('فشل تسجيل الخروج','bad'); user=null; session=null; updateAuthUI(); toast('تم تسجيل الخروج'); setCloudStatus('محلي فقط','warn'); }
  function updateAuthUI(){ $('authBox').style.display=user?'none':'block'; $('loggedBox').style.display=user?'block':'none'; setText('loggedEmail',user?.email||''); setCloudStatus(user?`متصل: ${user.email}`:'محلي فقط',user?'ok':'warn'); }

  function rowChalet(c){return {id:c.id,user_id:user.id,name:c.name,capacity:c.capacity,price:c.price,description:c.description||'',color:c.color||0,is_active:c.is_active!==false,created_at:c.created_at,updated_at:c.updated_at};}
  function rowBooking(b){return {id:b.id,user_id:user.id,booking_no:b.booking_no,chalet_id:b.chalet_id,customer_name:b.customer_name,customer_phone:b.customer_phone,check_in:b.check_in,check_out:b.check_out,nights:b.nights,guests:b.guests,total:b.total,paid:b.paid,status:b.status,notes:b.notes||'',created_at:b.created_at,updated_at:b.updated_at,deleted_at:b.deleted_at};}
  function fromCloudChalet(c){return {id:c.id,name:c.name,capacity:c.capacity,price:Number(c.price||0),description:c.description||'',color:c.color||0,is_active:c.is_active!==false,created_at:c.created_at,updated_at:c.updated_at,deleted_at:c.deleted_at||null};}
  function fromCloudBooking(b){return {id:b.id,booking_no:b.booking_no,chalet_id:b.chalet_id,customer_name:b.customer_name,customer_phone:b.customer_phone,check_in:b.check_in,check_out:b.check_out,nights:b.nights,guests:b.guests,total:Number(b.total||0),paid:Number(b.paid||0),status:b.status,notes:b.notes||'',created_at:b.created_at,updated_at:b.updated_at,deleted_at:b.deleted_at||null};}
  function newer(a,b){ return new Date(a?.updated_at||0).getTime() >= new Date(b?.updated_at||0).getTime(); }
  function mergeRows(localRows,cloudRows){ const m=new Map(); for(const r of localRows||[])m.set(r.id,r); for(const c of cloudRows||[]){const old=m.get(c.id); if(!old||newer(c,old))m.set(c.id,c);} return [...m.values()]; }
  async function pullCloud(){ if(!user||!supabase||!navigator.onLine) return; if(new URLSearchParams(location.search).get('localonly')==='1'||new URLSearchParams(location.search).get('safe')==='1') return; setCloudStatus('جاري المزامنة','warn'); const [ch,bo,se]=await Promise.all([supabase.from('chalets').select('*').eq('user_id',user.id),supabase.from('bookings').select('*').eq('user_id',user.id),supabase.from('app_settings').select('data,updated_at').eq('user_id',user.id).maybeSingle()]); if(ch.error||bo.error||se.error){console.error(ch.error||bo.error||se.error); setCloudStatus('فشل الاتصال، سنحاول لاحقًا','bad'); return;} const remoteCh=(ch.data||[]).map(fromCloudChalet); const remoteB=(bo.data||[]).map(fromCloudBooking);
    if(remoteCh.length+remoteB.length===0) return setCloudStatus('تم تجاهل نسخة سحابية فارغة','warn');
    if(remoteB.length < activeCount(state.bookings) && !confirm('النسخة السحابية أقل من المحلية. هل تريد المتابعة؟')) return;
    backupBeforeOverwrite('cloud_pull');
    state.chalets=mergeRows(state.chalets,remoteCh); state.bookings=mergeRows(state.bookings,remoteB); if(se.data?.data) state.settings={...state.settings,...se.data.data,updated_at:se.data.updated_at}; await saveLocalOnly(false); renderAll(); setCloudStatus('تمت المزامنة','ok'); }
  async function pushAllLocal(showMigrationMsg=false){ if(!user||!supabase||!navigator.onLine) return;
    if(activeCount(state.chalets)+activeCount(state.bookings)===0) return setCloudStatus('تم منع رفع نسخة فارغة','bad');
    if(/hussein|ali6/i.test(user.email||'') && activeCount(state.bookings)===0) return setCloudStatus('تم منع رفع فارغ لحساب حساس','bad'); setCloudStatus('جاري المزامنة','warn'); const chalets=state.chalets.filter(c=>!c.deleted_at).map(rowChalet); const bookings=state.bookings.map(rowBooking); if(chalets.length){const {error}=await supabase.from('chalets').upsert(chalets); if(error) throw error;} if(bookings.length){const {error}=await supabase.from('bookings').upsert(bookings); if(error) throw error;} const {error:se}=await supabase.from('app_settings').upsert({user_id:user.id,data:getSettings(),updated_at:now()}); if(se) throw se; await supabase.from('sync_log').insert({user_id:user.id,action:'sync_all',details:{chalets:chalets.length,bookings:bookings.length}}).catch(()=>{}); writeQueue([]); setCloudStatus('تمت المزامنة','ok'); if(showMigrationMsg) toast('تم نقل بياناتك الحالية إلى السحابة'); }
  async function startCloudSync(showMigrationMsg=false){ if(!user) return; try{await exportAutoBackup(); await pullCloud(); await pushAllLocal(showMigrationMsg); startRealtime();}catch(e){console.error(e); setCloudStatus('فشلت المزامنة، سنحاول لاحقًا','bad');} }
  function syncSoon(){ clearTimeout(syncTimer); syncTimer=setTimeout(processQueue,900); }
  async function processQueue(){ if(!user||!supabase) return setCloudStatus('محلي فقط','warn'); if(!navigator.onLine) return setCloudStatus('أنت غير متصل، سيتم الحفظ محليًا','warn'); if(syncing) return; syncing=true; setCloudStatus('جاري المزامنة','warn'); try{const q=readQueue(); for(const op of q){ if(op.type==='chalet'){const c=state.chalets.find(x=>x.id===op.id); if(c) await supabase.from('chalets').upsert(rowChalet(c));} if(op.type==='booking'){const b=state.bookings.find(x=>x.id===op.id); if(b) await supabase.from('bookings').upsert(rowBooking(b));} if(op.type==='settings') await supabase.from('app_settings').upsert({user_id:user.id,data:getSettings(),updated_at:now()}); } writeQueue([]); await pullCloud(); setCloudStatus('تمت المزامنة','ok'); }catch(e){console.error(e); const q=readQueue().map(x=>({...x,retry:(x.retry||0)+1})); writeQueue(q); setCloudStatus('فشلت المزامنة، سنحاول لاحقًا','bad'); setTimeout(processQueue,Math.min(30000,1000*Math.pow(2,Math.min(5,q[0]?.retry||1))));} finally{syncing=false;} }
  function startRealtime(){ if(!supabase||!user)return; realtime.forEach(ch=>supabase.removeChannel(ch)); realtime=[]; ['chalets','bookings','app_settings'].forEach(table=>{ const ch=supabase.channel(`${table}-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table,filter:`user_id=eq.${user.id}`},()=>pullCloud().catch(console.error)).subscribe(); realtime.push(ch); }); }
  async function cloudConflict(booking){ if(!user||!supabase||!navigator.onLine||booking.status!=='confirmed') return false; const {data,error}=await supabase.from('bookings').select('id').eq('user_id',user.id).eq('chalet_id',booking.chalet_id).eq('status','confirmed').is('deleted_at',null).lt('check_in',booking.check_out).gt('check_out',booking.check_in); if(error){console.error(error);return false;} return (data||[]).some(x=>x.id!==booking.id); }
  function localConflict(booking){ if(booking.status!=='confirmed') return false; return activeBookings().some(b=>b.id!==booking.id&&b.chalet_id===booking.chalet_id&&b.status==='confirmed'&&b.check_in<booking.check_out&&b.check_out>booking.check_in); }
  function validateBooking(b){ if(!b.customer_name)return'اسم العميل مطلوب'; if(!b.customer_phone)return'رقم الجوال مطلوب'; if(!b.chalet_id)return'اختر الشاليه'; if(!b.check_in||!b.check_out)return'اختر تاريخ الدخول والخروج'; if(nights(b.check_in,b.check_out)<=0)return'تاريخ الخروج يجب أن يكون بعد الدخول'; if(b.guests<1)return'عدد الضيوف لا يقل عن 1'; if(b.paid<0)return'المدفوع لا يمكن أن يكون سالب'; if(b.total<0)return'الإجمالي غير صحيح'; if(b.paid>b.total&&!confirm('المدفوع أكبر من الإجمالي. هل تريد المتابعة؟'))return'تم إلغاء الحفظ'; return''; }
  function collectBooking(){ const id=editingBookingId||uid(); const old=state.bookings.find(b=>b.id===id)||{}; return {id,booking_no:old.booking_no||bookingNo(),chalet_id:$('bkChalet').value,customer_name:$('bkName').value.trim(),customer_phone:$('bkPhone').value.trim(),check_in:$('bkIn').value,check_out:$('bkOut').value,nights:Number($('bkNights').value||0),guests:Math.max(1,Number($('bkGuests').value||1)),total:Number($('bkTotal').value||0),paid:Number($('bkPaid').value||0),status:$('bkStatus').value,notes:$('bkNotes').value.trim(),created_at:old.created_at||now(),updated_at:now(),deleted_at:null}; }
  async function saveBooking(){ const b=collectBooking(); const err=validateBooking(b); if(err) return toast(err,'bad'); if(localConflict(b)||await cloudConflict(b)) return toast('يوجد حجز مؤكد لنفس الشاليه في هذه الفترة. لا يمكن حفظ الحجز.','bad'); const idx=state.bookings.findIndex(x=>x.id===b.id); if(idx>=0)state.bookings[idx]=b; else state.bookings.push(b); closeSheets(); await saveAndQueue({type:'booking',id:b.id,action:'upsert'}); toast('تم الحفظ'); showView('book'); }
  async function deleteBooking(){ if(!editingBookingId||!confirm('حذف الحجز؟'))return; const b=state.bookings.find(x=>x.id===editingBookingId); if(b){b.deleted_at=now(); b.updated_at=now();} closeSheets(); await saveAndQueue({type:'booking',id:editingBookingId,action:'delete'}); toast('تم الحذف'); showView('book'); }
  function bookingNo(){ return `${new Date().getFullYear()}-${String(activeBookings().length+1).padStart(4,'0')}`; }
  function collectChalet(){ const id=editingChaletId||uid(); const old=state.chalets.find(c=>c.id===id)||{}; return {id,name:$('chName').value.trim(),capacity:Math.max(1,Number($('chCapacity').value||1)),price:Math.max(0,Number($('chPrice').value||0)),description:$('chDesc').value.trim(),color:selectedColor,is_active:true,created_at:old.created_at||now(),updated_at:now(),deleted_at:null}; }
  async function saveChalet(){ const c=collectChalet(); if(!c.name)return toast('اسم الشاليه مطلوب','bad'); const idx=state.chalets.findIndex(x=>x.id===c.id); if(idx>=0)state.chalets[idx]=c; else state.chalets.push(c); closeSheets(); await saveAndQueue({type:'chalet',id:c.id,action:'upsert'}); toast('تم الحفظ'); showView('chalet'); }
  async function deleteChalet(){ if(!editingChaletId||!confirm('حذف الشاليه؟'))return; if(activeBookings().some(b=>b.chalet_id===editingChaletId&&['confirmed','pending'].includes(b.status)))return toast('لا يمكن حذف شاليه عليه حجوزات حالية أو معلقة','bad'); const c=state.chalets.find(x=>x.id===editingChaletId); if(c){c.deleted_at=now(); c.is_active=false; c.updated_at=now();} closeSheets(); await saveAndQueue({type:'chalet',id:editingChaletId,action:'delete'}); toast('تم الحذف'); showView('chalet'); }
  function calcBookingFields(){ const n=Math.max(0,nights($('bkIn').value,$('bkOut').value)); $('bkNights').value=n; const ch=state.chalets.find(c=>c.id===$('bkChalet').value); if(!editingBookingId)$('bkTotal').value=n*(ch?.price||0); $('bkRemaining').value=money(Number($('bkTotal').value||0)-Number($('bkPaid').value||0)); }
  function openBooking(id=null){ if(!activeChalets().length)return toast('أضف شاليه أولاً','bad'); editingBookingId=id; $('bookingTitle').textContent=id?'تعديل الحجز':'حجز جديد'; $('bkChalet').innerHTML=activeChalets().map(c=>`<option value="${esc(c.id)}">${esc(c.name)} - ${money(c.price)} ر.س</option>`).join(''); const b=state.bookings.find(x=>x.id===id); if(b){$('bkName').value=b.customer_name;$('bkPhone').value=b.customer_phone;$('bkChalet').value=b.chalet_id;$('bkIn').value=b.check_in;$('bkOut').value=b.check_out;$('bkNights').value=b.nights;$('bkGuests').value=b.guests;$('bkTotal').value=b.total;$('bkPaid').value=b.paid;$('bkStatus').value=b.status;$('bkNotes').value=b.notes||'';$('deleteBooking').style.display='inline-flex';} else {const d=new Date(),o=new Date(Date.now()+86400000);$('bkName').value='';$('bkPhone').value='';$('bkChalet').value=activeChalets()[0].id;$('bkIn').value=todayISO(d);$('bkOut').value=todayISO(o);$('bkGuests').value=1;$('bkPaid').value=0;$('bkStatus').value='confirmed';$('bkNotes').value='';$('deleteBooking').style.display='none';editingBookingId=null;} calcBookingFields(); openSheet('bookingSheet'); }
  function openChalet(id=null){ editingChaletId=id; $('chaletTitle').textContent=id?'تعديل الشاليه':'شاليه جديد'; $('colorPicker').innerHTML=COLORS.map((c,i)=>`<button type="button" class="color" data-color="${i}" style="background:linear-gradient(135deg,${c[0]},${c[1]})"></button>`).join(''); qsa('[data-color]').forEach(btn=>btn.onclick=()=>selectColor(Number(btn.dataset.color))); const c=state.chalets.find(x=>x.id===id); if(c){$('chName').value=c.name;$('chCapacity').value=c.capacity;$('chPrice').value=c.price;$('chDesc').value=c.description||'';selectedColor=c.color||0;$('deleteChalet').style.display='inline-flex';}else{$('chName').value='';$('chCapacity').value=1;$('chPrice').value='';$('chDesc').value='';selectedColor=activeChalets().length%COLORS.length;$('deleteChalet').style.display='none';} selectColor(selectedColor); openSheet('chaletSheet'); }
  function selectColor(i){ selectedColor=i; qsa('[data-color]').forEach(x=>x.classList.toggle('on',Number(x.dataset.color)===i)); }
  function openSheet(id){ $('shade').classList.add('on'); $(id).classList.add('on'); }
  function closeSheets(){ $('shade').classList.remove('on'); qsa('.sheet').forEach(s=>s.classList.remove('on')); }
  function renderAll(){ brand(); renderHome(); renderBookings(); renderChalets(); renderCalendar(); renderSettings(); fillFilters(); }
  function brand(){ const s=getSettings(); document.documentElement.dataset.theme=state.theme||'dark'; setText('brandName',s.name); setText('brandTag',s.tag||'نظام إدارة الحجوزات'); $('themeBtn').textContent=state.theme==='light'?'☀':'☾'; }
  function renderHome(){ const t=todayISO(),wk=todayISO(new Date(Date.now()+7*86400000)),month=new Date().getMonth(),year=new Date().getFullYear(); setText('todayText',`${DAYS[new Date().getDay()]} ${fmtDate(new Date())}`); const bookings=activeBookings().filter(b=>b.status!=='cancelled'); setText('sToday',bookings.filter(b=>b.check_in<=t&&b.check_out>t).length); setText('sWeek',bookings.filter(b=>b.check_in>=t&&b.check_in<=wk).length); let rev=0,due=0,days=0; bookings.forEach(b=>{const d=parseDate(b.check_in); if(d.getMonth()===month&&d.getFullYear()===year)rev+=b.total||0; due+=Math.max(0,(b.total||0)-(b.paid||0)); days+=b.nights||0;}); setText('sRev',money(rev)); setText('sDue',money(due)); setText('sCh',activeChalets().length); setText('sOcc',activeChalets().length?Math.min(100,Math.round(days/(activeChalets().length*30)*100))+'%':'0%'); const nearest=bookings.filter(b=>b.check_out>=t).sort((a,b)=>a.check_in.localeCompare(b.check_in)).slice(0,6); $('upcomingList').innerHTML=nearest.length?nearest.map(bookingHTML).join(''):'<div class="empty">لا توجد حجوزات قادمة</div>'; bindBookingActions(); }
  function renderBookings(){ const search=($('bookingSearch')?.value||'').trim(),fs=$('filterStatus')?.value||'all',fc=$('filterChalet')?.value||'all',sort=$('sortBookings')?.value||'checkin_desc'; let rows=activeBookings(); const t=todayISO(); if(search)rows=rows.filter(b=>b.customer_name.includes(search)||b.customer_phone.includes(search)); if(fc!=='all')rows=rows.filter(b=>b.chalet_id===fc); if(fs!=='all'){if(fs==='today')rows=rows.filter(b=>b.check_in<=t&&b.check_out>t);else if(fs==='upcoming')rows=rows.filter(b=>b.check_in>t);else if(fs==='past')rows=rows.filter(b=>b.check_out<=t);else rows=rows.filter(b=>b.status===fs);} rows.sort((a,b)=>sort==='checkin_asc'?a.check_in.localeCompare(b.check_in):sort==='created_asc'?(a.created_at||'').localeCompare(b.created_at||''):sort==='created_desc'?(b.created_at||'').localeCompare(a.created_at||''):b.check_in.localeCompare(a.check_in)); $('bookingList').innerHTML=rows.length?rows.map(bookingHTML).join(''):'<div class="empty">لا توجد حجوزات</div>'; bindBookingActions(); }
  function bookingHTML(b){ const rem=Math.max(0,(b.total||0)-(b.paid||0)),cls=businessStatus(b); return `<div class="item"><div class="itop"><div><div class="name">${esc(b.customer_name)}</div><div class="meta"><span>${esc(chaletName(b.chalet_id))}</span><span class="dot"></span><span>${shortDate(b.check_in)} ← ${shortDate(b.check_out)}</span><span class="dot"></span><span>${b.nights} ليلة</span><span class="dot"></span><span>${b.guests} ضيف</span></div></div><div class="price">${money(b.total)} ر.س</div></div><div class="actions"><div><span class="badge ${esc(cls)}">${statusText(cls)}</span>${rem>0&&b.status!=='cancelled'?` <span class="badge pending">متبقي ${money(rem)}</span>`:''}</div><div><button class="btn outline mini" data-voucher="${esc(b.id)}">سند</button> <button class="btn outline mini" data-edit-booking="${esc(b.id)}">تعديل</button></div></div></div>`; }
  function renderChalets(){ $('chaletList').innerHTML=activeChalets().length?activeChalets().map(c=>{const col=COLORS[c.color||0]; return `<div class="item" style="padding:0"><div class="chbanner" style="--c1:${col[0]};--c2:${col[1]}"></div><div class="chbody"><div class="itop"><div><div class="name">${esc(c.name)}</div><div class="meta"><span>👥 ${c.capacity}</span><span class="dot"></span><span>${money(c.price)} ر.س / ليلة</span></div></div><button class="btn outline mini" data-edit-chalet="${esc(c.id)}">تعديل</button></div><p class="sub" style="margin-top:8px">${esc(c.description||'')}</p></div></div>`;}).join(''):'<div class="empty">أضف أول شاليه</div>'; qsa('[data-edit-chalet]').forEach(b=>b.onclick=()=>openChalet(b.dataset.editChalet)); }
  function renderCalendar(){ const rows=activeBookings().filter(b=>['confirmed','pending'].includes(b.status)).sort((a,b)=>a.check_in.localeCompare(b.check_in)); $('calendarList').innerHTML=rows.length?rows.map(b=>`<div class="item"><div class="itop"><div><div class="name">${esc(chaletName(b.chalet_id))}</div><div class="meta"><span>${esc(b.customer_name)}</span><span class="dot"></span><span>${fmtDate(b.check_in)} إلى ${fmtDate(b.check_out)}</span></div></div><span class="badge ${b.status}">${statusText(b.status)}</span></div></div>`).join(''):'<div class="empty">لا توجد حجوزات في التقويم</div>'; }
  function renderSettings(){ const s=getSettings(); $('setName').value=s.name; $('setTag').value=s.tag; $('setPhone').value=s.phone; $('setIn').value=s.checkIn; $('setOut').value=s.checkOut; $('setTerms').value=s.terms; $('supabaseUrl').value=s.supabaseUrl||window.CHALETS_SUPABASE_URL||''; $('supabaseAnon').value=s.supabaseAnon||window.CHALETS_SUPABASE_ANON_KEY||''; updateAuthUI(); }
  function fillFilters(){ const cur=$('filterChalet').value||'all'; $('filterChalet').innerHTML='<option value="all">كل الشاليهات</option>'+activeChalets().map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join(''); $('filterChalet').value=[...$('filterChalet').options].some(o=>o.value===cur)?cur:'all'; }
  function bindBookingActions(){ qsa('[data-edit-booking]').forEach(b=>b.onclick=()=>openBooking(b.dataset.editBooking)); qsa('[data-voucher]').forEach(b=>b.onclick=()=>showVoucher(b.dataset.voucher)); }
  function showView(v){ qsa('.view').forEach(x=>x.classList.toggle('on',x.id===`v-${v}`)); qsa('.tab button').forEach(x=>x.classList.toggle('on',x.dataset.view===v)); $('fab').style.display=['settings','voucher'].includes(v)?'none':'block'; renderAll(); scrollTo(0,0); }
  function showVoucher(id){ const b=state.bookings.find(x=>x.id===id); if(!b)return; const s=getSettings(),rem=Math.max(0,b.total-b.paid),text=voucherText(b); $('voucher').innerHTML=`<div class="voucher"><div class="vtop"><h2>${esc(s.name)}</h2><p>${esc(s.tag||'سند حجز')}</p></div><div class="vtitle">سند حجز رقم ${esc(b.booking_no)}</div><div class="vbody">${vrow('اسم العميل',b.customer_name)}${vrow('الجوال',b.customer_phone)}${vrow('الشاليه',chaletName(b.chalet_id))}${vrow('الدخول',fmtDate(b.check_in)+' - '+esc(s.checkIn))}${vrow('الخروج',fmtDate(b.check_out)+' - '+esc(s.checkOut))}${vrow('الليالي',b.nights)}${vrow('الضيوف',b.guests)}${vrow('الإجمالي',money(b.total)+' ر.س')}${vrow('المدفوع',money(b.paid)+' ر.س')}${vrow('المتبقي',money(rem)+' ر.س')}${vrow('الحالة',statusText(b.status))}${vrow('ملاحظات',b.notes||'—')}<h3>الشروط</h3><p>${esc(s.terms).replace(/\n/g,'<br>')}</p>${vrow('رقم التواصل',s.phone||'—')}<div class="vactions no-print"><button class="btn primary" onclick="window.print()">طباعة</button><button class="btn outline" id="copyVoucher">نسخ</button><a class="btn outline" target="_blank" href="https://wa.me/?text=${encodeURIComponent(text)}">واتساب</a></div></div></div>`; $('copyVoucher').onclick=()=>navigator.clipboard.writeText(text).then(()=>toast('تم نسخ السند')); showView('voucher'); }
  function vrow(a,b){return `<div class="vrow"><span>${esc(a)}</span><b>${esc(b)}</b></div>`}
  function voucherText(b){ const s=getSettings(),rem=Math.max(0,b.total-b.paid); return `${s.name}\nسند حجز رقم ${b.booking_no}\nالعميل: ${b.customer_name}\nالجوال: ${b.customer_phone}\nالشاليه: ${chaletName(b.chalet_id)}\nالدخول: ${fmtDate(b.check_in)} ${s.checkIn}\nالخروج: ${fmtDate(b.check_out)} ${s.checkOut}\nالليالي: ${b.nights}\nالضيوف: ${b.guests}\nالإجمالي: ${money(b.total)} ر.س\nالمدفوع: ${money(b.paid)} ر.س\nالمتبقي: ${money(rem)} ر.س\nالحالة: ${statusText(b.status)}\n${b.notes?`ملاحظات: ${b.notes}\n`:''}${s.terms}\nالتواصل: ${s.phone}`; }
  async function saveSettings(){ const old=getSettings(); state.settings={...old,name:$('setName').value.trim()||'الشاليهات',tag:$('setTag').value.trim(),phone:$('setPhone').value.trim(),checkIn:$('setIn').value||'15:00',checkOut:$('setOut').value||'12:00',terms:$('setTerms').value.trim(),supabaseUrl:$('supabaseUrl').value.trim(),supabaseAnon:$('supabaseAnon').value.trim(),updated_at:now()}; await saveAndQueue({type:'settings',action:'upsert'}); initSupabase(); toast('تم الحفظ'); }
  async function saveCloudConfig(){ state.settings={...getSettings(),supabaseUrl:$('supabaseUrl').value.trim(),supabaseAnon:$('supabaseAnon').value.trim(),updated_at:now()}; await saveLocalOnly(); if(initSupabase()) await initAuth(); toast('تم حفظ إعدادات Supabase'); }
  async function exportAutoBackup(){ localStorage.setItem('chalets_auto_backup_before_cloud',JSON.stringify({exported_at:now(),state})); }
  function exportBackup(){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify({exported_at:now(),state},null,2)],{type:'application/json'})); a.download='chalets-backup-'+todayISO()+'.json'; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); }

  function renderRecoveryList(){ const cands=listRecoveryCandidates(); const box=$('recoveryList'); if(!box) return; if(!cands.length){ box.innerHTML='<div class="item">لا توجد نسخ قابلة للقراءة.</div>'; return; } box.innerHTML=cands.map((c,i)=>`<label class="item" style="display:block"><input type="radio" name="recoveryPick" value="${i}" ${i===0?'checked':''}> <b>${esc(c.key)}</b><div class="small">شاليهات: ${c.chalets} · حجوزات: ${c.bookings} ${c.tulum?'· تولوم':''} ${c.sky?'· سكاي':''} ${c.seed?'· نسخة تجريبية':''}</div></label>`).join(''); renderRecoveryList._cands=cands; }
  async function applyRecoverySelection(){ const cands=renderRecoveryList._cands||[]; const picked=document.querySelector('input[name="recoveryPick"]:checked'); if(!picked) return toast('اختر نسخة أولاً','bad'); const cand=cands[Number(picked.value)]; if(!cand) return; if(!confirm('تأكيد استرجاع النسخة المحددة؟')) return; backupBeforeOverwrite('manual_recovery'); state=normalizeOld(cand.state); await saveLocalOnly(); renderAll(); toast('تم الاسترجاع بنجاح'); }

  function importBackup(e){ const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=async()=>{try{const obj=JSON.parse(r.result); state=normalizeOld(obj.state||obj.data||obj); await saveLocalOnly(); renderAll(); toast('تم استيراد النسخة');}catch(err){console.error(err); toast('ملف النسخة غير صحيح','bad');}}; r.readAsText(f); }
  async function resetLocal(){ if(!confirm('سيتم حذف البيانات المحلية فقط. هل أنت متأكد؟'))return; await exportAutoBackup(); state=structuredClone(DEFAULT_STATE); seed(); await saveLocalOnly(); renderAll(); toast('تم حذف البيانات المحلية'); }
  function bindEvents(){ qsa('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view)); qsa('[data-open-booking]').forEach(b=>b.onclick=()=>openBooking()); qsa('[data-open-chalet]').forEach(b=>b.onclick=()=>openChalet()); qsa('[data-close]').forEach(b=>b.onclick=closeSheets); $('shade').onclick=closeSheets; $('saveBooking').onclick=saveBooking; $('deleteBooking').onclick=deleteBooking; $('saveChalet').onclick=saveChalet; $('deleteChalet').onclick=deleteChalet; ['bkChalet','bkIn','bkOut','bkTotal','bkPaid'].forEach(id=>$(id).addEventListener('input',calcBookingFields)); $('themeBtn').onclick=async()=>{state.theme=state.theme==='light'?'dark':'light'; await saveAndQueue({type:'settings',action:'theme'});}; $('cloudTop').onclick=()=>showView('settings'); ['bookingSearch','filterStatus','filterChalet','sortBookings'].forEach(id=>$(id).addEventListener('input',renderBookings)); $('saveSettings').onclick=saveSettings; $('saveCloudConfig').onclick=saveCloudConfig; $('sendLogin').onclick=sendMagicLink; $('logoutBtn').onclick=logout; $('syncNow').onclick=()=>{ if(confirm('تأكيد رفع/مزامنة البيانات مع السحابة؟')) startCloudSync(false); }; $('exportBackup').onclick=exportBackup; $('importBackupBtn').onclick=()=>$('importBackup').click(); $('importBackup').onchange=importBackup; $('resetLocal').onclick=resetLocal; qsa('#scanRecovery,#showRecovery').forEach(b=>b.onclick=renderRecoveryList); $('applyRecovery').onclick=applyRecoverySelection; window.addEventListener('online',()=>{toast('عاد الاتصال'); processQueue();}); window.addEventListener('offline',()=>{setCloudStatus('غير متصل','warn'); toast('أنت غير متصل، تم الحفظ محليًا','bad');}); window.addEventListener('focus',()=>{if(user)pullCloud();}); setInterval(()=>{if(user&&navigator.onLine)processQueue();},30000); }
  async function init(){ await loadLocal(); bindEvents(); renderAll(); await initAuth(); }
  init().catch(e=>{console.error(e); toast('حدث خطأ أثناء تشغيل التطبيق','bad');});
})();
